name: Release

on:
  push:
    branches: [main]
    paths-ignore:
      - 'docs/**'
      - 'examples/**'
      - 'assets/**'
      - '**.md'
      - '!.changeset/**'
      - 'LICENSE'

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.32.3
          # run_install: true
      - name: Use Node.js 17
        uses: actions/setup-node@v2
        with:
          node-version: '17.8.0'
          cache: 'pnpm'
      - name: Pick the right npm version
        # * See: https://github.com/pnpm/pnpm/issues/4348
        run: npm install --global npm@8.4
      - name: Install dependencies
        run: pnpm install
      - name: Create PR or Publish release
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm run ci:version
          commit: 'chore: update versions'
          title: 'chore: update versions'
          publish: pnpm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
